set_pns_commit_mode true
# Starting to commit core rings
create_power_straps  -direction vertical  -start_at 53.680 -nets VDD -layer M8 -width 0.480 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 54.880 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 0.720 -nets VDD -layer M8 -width 0.480 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 54.880 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 0.930 -nets VDD -layer M9 -width 0.900 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 53.920 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 54.430 -nets VDD -layer M9 -width 0.900 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 53.920 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 52.960 -nets VSS -layer M8 -width 0.480 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 53.500 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 1.440 -nets VSS -layer M8 -width 0.480 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 53.500 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 2.310 -nets VSS -layer M9 -width 0.900 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 53.200 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 53.050 -nets VSS -layer M9 -width 0.900 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 53.200 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
# Starting to commit block rings
# Starting to commit metal8 straps for net VDD
create_power_straps  -direction vertical  -start_at 3.740 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 54.880 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 5.900 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 54.880 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 8.060 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 54.880 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 10.220 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 54.880 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 12.380 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 54.880 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 14.540 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 54.880 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 17.060 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 54.880 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 19.220 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 54.880 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 21.380 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 54.880 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 23.540 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 54.880 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 25.700 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 54.880 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 27.860 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 54.880 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 30.020 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 54.880 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 32.540 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 54.880 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 34.700 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 54.880 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 36.860 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 54.880 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 39.020 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 54.880 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 41.180 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 54.880 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 43.340 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 54.880 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 45.500 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 54.880 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 48.020 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 54.880 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 50.180 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 54.880 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal8 straps for net VSS
create_power_straps  -direction vertical  -start_at 4.220 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 53.500 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 6.380 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 53.500 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 8.540 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 53.500 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 10.700 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 53.500 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 12.860 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 53.500 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 15.020 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 53.500 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 17.540 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 53.500 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 19.700 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 53.500 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 21.860 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 53.500 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 24.020 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 53.500 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 26.180 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 53.500 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 28.340 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 53.500 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 30.500 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 53.500 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 33.020 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 53.500 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 35.180 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 53.500 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 37.340 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 53.500 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 39.500 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 53.500 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 41.660 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 53.500 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 43.820 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 53.500 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 45.980 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 53.500 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 48.500 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 53.500 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 50.660 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 2.210 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 53.500 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal9 straps for net VDD
create_power_straps  -direction horizontal  -start_at 5.035 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 2.930 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 53.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 8.035 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 2.930 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 53.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 11.035 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 2.930 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 53.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 14.035 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 2.930 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 53.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 17.035 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 2.930 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 53.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 20.035 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 2.930 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 53.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 22.535 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 2.930 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 53.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 25.535 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 2.930 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 53.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 28.535 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 2.930 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 53.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 31.535 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 2.930 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 53.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 34.535 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 2.930 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 53.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 37.535 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 2.930 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 53.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 40.535 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 2.930 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 53.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 43.035 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 2.930 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 53.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 46.035 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 2.930 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 53.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 49.035 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 2.930 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 53.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal9 straps for net VSS
create_power_straps  -direction horizontal  -start_at 5.965 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 2.930 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 53.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 8.965 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 2.930 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 53.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 11.965 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 2.930 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 53.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 14.965 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 2.930 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 53.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 17.965 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 2.930 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 53.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 20.965 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 2.930 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 53.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 23.465 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 2.930 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 53.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 26.465 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 2.930 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 53.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 29.465 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 2.930 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 53.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 32.465 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 2.930 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 53.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 35.465 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 2.930 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 53.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 38.465 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 2.930 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 53.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 41.465 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 2.930 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 53.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 43.965 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 2.930 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 53.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 46.965 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 2.930 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 53.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 49.965 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 2.930 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 53.200 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
set_pns_commit_mode false
