set_pns_commit_mode true
# Starting to commit core rings
create_power_straps  -direction vertical  -start_at 125.520 -nets VDD -layer M8 -width 0.480 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 126.080 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 0.720 -nets VDD -layer M8 -width 0.480 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 126.080 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 0.930 -nets VDD -layer M9 -width 0.900 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 125.760 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 125.630 -nets VDD -layer M9 -width 0.900 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 125.760 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 124.800 -nets VSS -layer M8 -width 0.480 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 124.700 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 1.440 -nets VSS -layer M8 -width 0.480 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 124.700 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 2.310 -nets VSS -layer M9 -width 0.900 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 125.040 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 124.250 -nets VSS -layer M9 -width 0.900 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 125.040 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
# Starting to commit block rings
# Starting to commit metal8 straps for net VDD
create_power_straps  -direction vertical  -start_at 6.180 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 126.080 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 10.860 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 126.080 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 15.540 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 126.080 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 20.220 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 126.080 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 24.900 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 126.080 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 29.580 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 126.080 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 34.620 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 126.080 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 39.300 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 126.080 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 43.980 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 126.080 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 48.660 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 126.080 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 53.340 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 126.080 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 58.020 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 126.080 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 62.700 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 126.080 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 67.380 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 126.080 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 72.060 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 126.080 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 77.100 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 126.080 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 81.780 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 126.080 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 86.460 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 126.080 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 91.140 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 126.080 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 95.820 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 126.080 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 100.500 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 126.080 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 105.180 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 126.080 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 109.860 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 126.080 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 114.540 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 126.080 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 119.580 -nets VDD  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 126.080 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal8 straps for net VSS
create_power_straps  -direction vertical  -start_at 6.660 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 124.700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 11.340 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 124.700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 16.020 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 124.700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 20.700 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 124.700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 25.380 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 124.700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 30.060 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 124.700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 35.100 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 124.700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 39.780 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 124.700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 44.460 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 124.700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 49.140 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 124.700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 53.820 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 124.700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 58.500 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 124.700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 63.180 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 124.700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 67.860 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 124.700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 72.540 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 124.700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 77.580 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 124.700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 82.260 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 124.700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 86.940 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 124.700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 91.620 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 124.700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 96.300 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 124.700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 100.980 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 124.700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 105.660 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 124.700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 110.340 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 124.700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 115.020 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 124.700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 120.060 -nets VSS  -layer M8 -width 0.240 -pitch_within_group 4.720 -start_low_ends coordinate  -start_low_ends_coordinate 1.860 -start_high_ends coordinate  -start_high_ends_coordinate 124.700 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal9 straps for net VDD
create_power_straps  -direction horizontal  -start_at 7.035 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 125.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 11.535 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 125.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 16.035 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 125.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 21.035 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 125.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 25.535 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 125.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 30.035 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 125.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 35.035 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 125.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 39.535 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 125.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 44.035 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 125.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 48.535 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 125.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 53.535 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 125.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 58.035 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 125.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 62.535 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 125.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 67.535 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 125.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 72.035 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 125.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 76.535 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 125.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 81.535 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 125.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 86.035 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 125.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 90.535 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 125.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 95.035 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 125.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 100.035 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 125.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 104.535 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 125.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 109.035 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 125.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 114.035 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 125.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 118.535 -nets VDD  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 0.480 -start_high_ends coordinate  -start_high_ends_coordinate 125.760 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal9 straps for net VSS
create_power_straps  -direction horizontal  -start_at 7.965 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 125.040 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 12.465 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 125.040 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 16.965 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 125.040 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 21.965 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 125.040 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 26.465 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 125.040 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 30.965 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 125.040 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 35.965 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 125.040 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 40.465 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 125.040 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 44.965 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 125.040 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 49.465 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 125.040 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 54.465 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 125.040 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 58.965 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 125.040 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 63.465 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 125.040 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 68.465 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 125.040 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 72.965 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 125.040 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 77.465 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 125.040 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 82.465 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 125.040 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 86.965 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 125.040 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 91.465 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 125.040 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 95.965 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 125.040 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 100.965 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 125.040 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 105.465 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 125.040 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 109.965 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 125.040 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 114.965 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 125.040 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 119.465 -nets VSS  -layer M9 -width 0.450 -pitch_within_group 4.650 -start_low_ends coordinate  -start_low_ends_coordinate 1.200 -start_high_ends coordinate  -start_high_ends_coordinate 125.040 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
set_pns_commit_mode false
