ICV_HOME_DIR      = /usr/local/synopsys/icvalidator/K-2015.12-3
WORKING_DIR       = .
INLIB             = mylibrary
INLIB_PATH        = 
OUTLIB            = run_details/ringOscillator
OUTLIB_PATH       = .
BLOCK             = ringOscillator
PYDB_PATH         = TOPCELLNAME_err
RUN_DETAILS_DIR   = run_details
NDB_PATH          = run_details/.ndb
FORMAT            = OPENACCESS
EVACCESS_PATH     = TOPCELLNAME_err
SCHEMATIC         = ringOscillator.sch_out
SCHEMATIC_FORMAT  = ICV
GROUP_PATH        = run_details/group
RUNSET_FILE_NAME  = rules.lvs.9m_saed90_lvs.lvs.rs
ENVIRONMENT STRING  SAED90_PDK = /usr/local/synopsys/pdk/SAED_PDK90nm
EXTRACTION_FLOW   = true
COMPARE_DIR       = run_details/compare
COMPARE_NETLIST_FLOW = ICV
STATUS_COMPARE    = 0
